# Generated by Django 5.2.14 on 2026-05-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
