# Generated by Django 5.2.14 on 2026-06-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_trashmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrashModel',
        ),
    ]
